require_relative '../item'
require_relative '../music_album'
require_relative '../genre'
require_relative '../music_genre_op'
require_relative '../book'
require_relative '../label'
require_relative '../books_operation'
